GET:http://localhost:3000/api/sauces/login

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RldXNlQHRlc3RlLmNvbSIsImlhdCI6MTY0NzgyMTMwMiwiZXhwIjoxNjQ3OTA3NzAyfQ.D6ynR79BMYp1d6bPEdF31HXBNkRXIWZLH2wb4HJf-2o